#coding=utf8

URL_PREFIX_XIAOQU = 'http://sh.lianjia.com/xiaoqu'
NUM_ITEMS_PER_PAGE = 20

DISTRICTS = [
    #('浦东', '御桥', 'yuqiao1'),
    #('浦东', '北蔡', 'beicai'),
    #('浦东', '碧云', 'biyun'),
    #('浦东', '曹路', 'caolu'),
    #('浦东', '川沙', 'chuansha'),
    #('浦东', '大团镇', 'datuanzhen'),
    #('浦东', '高东', 'gaodong'),
    #('浦东', '高行', 'gaohang'),
    #('浦东', '花木', 'huamu'),
    #('浦东', '惠南', 'huinan'),
    #('浦东', '合庆', 'geqing'),
    #('浦东', '航头', 'hangtou'),
    #('浦东', '金桥', 'jinqiao'),
    #('浦东', '金杨', 'jinyang'),
    #('浦东', '康桥', 'kangqiao'),
    #('浦东', '临港新城', 'lingangxincheng'),
    #('浦东', '老港镇', 'laogangzhen'),
    #('浦东', '陆家嘴', 'lujiazui'),
    #('浦东', '联洋', 'lianyang'),
    #('浦东', '泥城镇', 'nichengzhen'),
    #('浦东', '南码头', 'nanmatou'),
    #('浦东', '世博', 'shibo'),
    #('浦东', '三林', 'sanlin'),
    #('浦东', '书院镇', 'shuyuanzhen'),
    #('浦东', '塘桥', 'tangqiao'),
    #('浦东', '唐镇', 'tangzhen'),
    #('浦东', '潍坊', 'weifang'),
    #('浦东', '外高桥', 'waigaoqiao'),
    #('浦东', '万祥镇', 'wanxiangzhen'),
    #('浦东', '新场', 'xinchang'),
    #('浦东', '宣桥', 'xuanqiao'),
    #('浦东', '杨东', 'yangdong'),
    #('浦东', '洋泾', 'yangjing'),
    #('浦东', '源深', 'yuanshen'),
    #('浦东', '张江', 'zhangjiang'),
    #('浦东', '周浦', 'zhoupu'),
    #('浦东', '祝桥', 'zhuqiao'),
    
    #('闵行', '春申', 'chunshen'),
    #('闵行', '古美', 'gumei'),
    #('闵行', '华漕', 'huacao'),
    #('闵行', '航华', 'hanghua'),
    #('闵行', '静安新城', 'jinganxincheng'),
    #('闵行', '金汇', 'jinhui'),
    #('闵行', '金虹桥', 'jinhongqiao'),
    #('闵行', '龙柏', 'longbai'),
    #('闵行', '老闵行', 'laominhang'),
    #('闵行', '梅陇', 'meilong'),
    #('闵行', '马桥', 'maqiao'),
    #('闵行', '浦江', 'pujiang1'),
    #('闵行', '七宝', 'qibao'),
    #('闵行', '吴泾', 'wujing'),
    #('闵行', '莘庄', 'shenzhuang'),
    #('闵行', '颛桥', 'zhuanqiao'),

]